---
- hosts: web
  become: yes

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - docker.io
          - python3-pip
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Install Docker Python module
      pip:
        name: docker

    - name: Pull custom Docker image
      docker_image:
        name: prmaodhraj/myapp
        tag: latest
        source: pull

    - name: Stop containers using port 80
      shell: docker ps -q --filter "publish=80" | xargs -r docker rm -f

    - name: Run custom Docker container
      docker_container:
        name: pramodh-app
        image: prmaodhraj/myapp:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"
